### ISSUE TITLE
Complete V1 of project

### ISSUE THREAD

**Issue by vejendla** [vejendla/dbt-citibike#1]
This issue contains the things I need to work on to complete V1 of this project.

**Goal**

The goal of this project is to use CitiBike trip data and the MTA GTFS feed to identify areas where bus service could be expanded or improved. This project uses CitiBike trip data from January to May of 2018 (taken from a public BigQuery dataset) and uses a recent export of Manhattan bus routes. 

My learning goals with this project are to:

1. Learn DBT
2. Strengthen my SQL skills
3. Demonstrate expertise working with GTFS data

**Technical criteria for success**

This project was also started during the first DBT community learn, hosted by DBT labs in a hybrid format in NYC in April/May 2023. Thus, this project should also fulfill the project success criteria outlined in that project. Here they are:

- [ ] vejendla/dbt-citibike#2
- [ ] vejendla/dbt-citibike#11
- [ ] vejendla/dbt-citibike#10
- [ ] vejendla/dbt-citibike#9
- [ ] vejendla/dbt-citibike#8
- [ ] vejendla/dbt-citibike#7
- [ ] vejendla/dbt-citibike#13
- [ ] vejendla/dbt-citibike#14
- [ ] vejendla/dbt-citibike#12
- [ ] vejendla/dbt-citibike#6
- [ ] vejendla/dbt-citibike#5
- [ ] vejendla/dbt-citibike#4

**Conceptual criteria for success**

Independent of the criteria above, here are some criteria I have for success. Specifically, I would be happy if project does the following:

- [ ] vejendla/dbt-citibike#3
- [ ] displays the highest ridership CitiBike segments
- [ ] for each high ridership segment, joins the starting and end bus stations based on `stations_from_trip_data`
- [ ] identifies at least 5 corresponding bus routes in the top 25% of Citibike trip segments, by joining on `stop_times`
